### PR TITLE
Split kernel scriptlets into separate sub-package

### PR DESCRIPTION
**Pull request by lnussel**
Allows to replace them with noops for systems based on file triggers only

### CODE REVIEW

**Comment by lnussel** [comment]
test build with kernel and prjconf modifications in https://build.opensuse.org/project/show/home:lnussel:branches:network
still takes time to finish
See also https://bugzilla.opensuse.org/show_bug.cgi?id=1205149

**Comment by lnussel** [comment]
the failed obs build for 15.4 look unrelated to the change

**Comment by mwilck** [comment]
Yes indeed, the 15.4 failure is unrelated.

So how is the prjconf change going?

**Comment by lnussel** [comment]
release engineering will have to take care of that for the staging and when accepting the submission. Nothing we can do here other than telling them.

**Comment by lnussel** [comment]
ping?

**Comment by mwilck** [comment]
pong - I haven't followed the release engineering process, did you?

**Comment by lnussel** [comment]
just submit then point the release engineer in charge at https://bugzilla.opensuse.org/show_bug.cgi?id=1205149#c2

**Comment by mwilck** [comment]
I'd like to reverse the order of steps here. Last time my submission was rejected because of the build failures in question. And tbh I don't even know who the release engineers would be that I have to contact. Dominique?

**Comment by lnussel** [comment]
for example, yes. Both Fabian and Dominique are CC'd in the bug so they are aware and didn't object the suggestion there.

**Comment by mwilck** [comment]
Well, let's see how it goes, then.

**Pull request merged**
