### PR TITLE
Unify ppc64 and ppc64le

### PR DESCRIPTION
**Pull request by hramrach**

### CODE REVIEW

**Comment by mwilck** [comment]
Do we need ppc64 at all?

**Comment by hramrach** [comment]
In Tumbleweed

**Comment by mwilck** [comment]
Hm, just saw that TW even still has "ppc" ... does that mean I have to undo the removal of `modprobe.conf.ppc` ?

**Comment by hramrach** [comment]
And is that an actual release or is it something we build to have 32bit libraries?

**Comment by mwilck** [comment]
I don't know, I'm asking you :grin:
I just saw that there are repositiories with arch "ppc" for openSUSE:Factory:PowerPC.

**Comment by hramrach** [comment]
I see only 64bit releases http://download.opensuse.org/ports/ppc/tumbleweed/iso/

**Comment by mwilck** [comment]
So, for my understanding - the `ppc` arch is really only a compatibility layer to allow execution of 32bit binaries on `ppc64{,le}`?

**Comment by hramrach** [comment]
on pp64 only. there is no 32bit compatibility on ppc64le

**Comment by mwilck** [comment]
Thanks. So, no need to resurrect `ppc`. Thanks for the clarification.

**Pull request merged**
