### PR TITLE
sles12-sp5 Import kernel scriptlets from kernel-source.

### PR DESCRIPTION
**Pull request by hramrach**
Done as loose files - not sure the SourceX listing handles directories

### CODE REVIEW

**Comment by mwilck** [comment]
> Done as loose files - not sure the SourceX listing handles directories

I don't understand, please explain why you can't do this like in the other distros.

**Comment by hramrach** [comment]
AFAICT the files are tracked as loose sources in the .spec file rather than a tarball.

**Comment by mwilck** [comment]
Please hold on. I'll see if I can change the SLE12 spec file to match the SLE15 one. That's more work for me but better for merging these scripts.

**Comment by hramrach** [comment]
There is already modprobe.conf directory packaged as archive so I copied that part

**Comment by hramrach** [comment]
might be a hard sell to maintenance moving all files into a tarball in a MU but we can try

**Comment by mwilck** [comment]
The entire change will be a hard sell. But this is just a rearrangement of the sources. We must separate these steps logically - first change the spec file to match SLE15, then add the kernel scriptlets. If we do that, we could prove to maintenance that the build result of the the 1 step is identical to the 2nd step.

**Pull request merged**
