### PR TITLE
Sles15 sp2

### PR DESCRIPTION
**Pull request by hramrach**

### CODE REVIEW

**Comment by hramrach** [comment]
is there some way to trigger the OBS workflow?

**Comment by mwilck** [comment]
> is there some way to trigger the OBS workflow?

IIUC the target branch must contain a workflow definition already (this is for security reasons, PR authors shouldn't be able to create arbitrary workflows). The SLE branches don't have workflows yet, the entire feature is experimental. And I don't even have OBS repositories for SLE *s-m-t* (only IBS).

**Comment by hramrach** [comment]
The Factory workflow built against everything anyway so it could be reused for SLE with minimal change.

**Comment by mwilck** [comment]
It doesn't matter much, but you're missing 6596bae ("rpm-script: link config also into /boot (boo#1189879)")

> The Factory workflow built against everything anyway so it could be reused for SLE with minimal change.

Sure. I'd just need to add the `workflows.yml`. I just didn't yet.

**Pull request merged**
