### PR TITLE
add udev rules from system-tuning-common-SUSE

### PR DESCRIPTION
**Pull request by tblume**
this was discussed in jira#SLE-21032
afterwards we should drop system-tuning-common-SUSE

### CODE REVIEW

**Comment by mwilck** [comment]
Is this decided already?

**Comment by tblume** [comment]
> Is this decided already?

Franck and I agree, the decision from PM seems to be still outstanding.

**Comment by mwilck** [comment]
as this mainly concerns openSUSE for now, I also raised the question on #discuss-opensuse in slack.

**Comment by mwilck** [comment]
Note that whenever files are migrated between packages, they need to be *removed* in the old package first before they can be added in another; otherwise file conflicts will be raised by the bots. And we need `Obsoletes:` and `Provides:` tags.

**Pull request merged**
