### PR TITLE
suse-module-tools: modprobe.conf cleanup

### PR DESCRIPTION
**Pull request by mwilck**
Remove some obsolete files and configuration directives.

### CODE REVIEW

**Review by hramrach — APPROVED** [review]
LGTM

Thanks

**Comment by hramrach** [comment]
What is installed on ppc64 once ppc is removed?

**Comment by hramrach** [comment]
See #22 for followup

**Review by danimo — APPROVED** [review]
LGTM (but can only partly judge on the platform specific parts)

**Pull request merged**
